AWSTemplateFormatVersion: "2010-09-09"
Description: ec2 web app 
Resources:
        webappec2:
            Type: "AWS::EC2::Instance"
            Properties: 
                ImageId: "ami-0b8fd93c15b2c81ce" 
                InstanceType: t2.micro
                KeyName: "stockkey"
                DisableApiTermination: True 
                Tags: 
                      - Key: "Name"
                        Value: "Webserver"